# Файл с еmail
file:
  path: src/main/resources/clients.txt

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        queue-capacity: 1000

  # Настройки почты
  mail:
    host: smtp.mail.ru
    port: 587
    username: firstkam@mail.ru

    password: "SMLURV61HwvwbiU8hMjV"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#          alt-mail:
#        username: sendler.mail@mail.ru
#        password: 7FcByreg4y9YufqsZ8ra


  #        username: firstkam@mail.ru
#        password: "SMLURV61HwvwbiU8hMjV"
#  nedvijimostprosto@gmail.com
#  leihgsymllsdnkie

  boot:
    admin:
      client:
        url: http://localhost:${server.port}/admin
      context-path: /admin

# Путь к HTML-шаблону
html:
  template:
    path: classpath:templates/offer_123.html

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081 # Порт для Spring Boot Admin Server
